### ISSUE TITLE
Visualizer - Utilize metadata during chart creation

### ISSUE THREAD

**Issue by pitsios-s** [aegisbigdata/documentation#80] opened 2018-10-15 10:43 UTC
Variable data types and units are needed.

**Comment by FabiApfelkern** [comment] 2019-04-18 08:46
@pitsios-s Is this a duplicate of https://github.com/aegisbigdata/documentation/issues/104?

**Comment by pitsios-s** [comment] 2019-04-18 11:56
Actually not. This issue refers to the use of metadata to fill some additional information in chart axis labels, like for example the units.

**Closed** 2019-07-01 15:04 UTC
Labels: FOKUS, LINKED DATA, UBITECH, Visualizer
